---
- name: Assignment 4 - Bring environment up and run initial migrations
  hosts: localhost
  connection: local
  vars:
    mysql_root_password: "rootpass"
    db_name: "subscriptions"
    db_user: "sub_user"
    db_pass: "sub_pass"
    mysql_host: "127.0.0.1"
    mysql_port: 3306

  tasks:
    - name: Ensure MySQL container is running (docker)
      ansible.builtin.shell: |
        docker inspect a4-mysql >/dev/null 2>&1 || \
        docker run --name a4-mysql \
          -e MYSQL_ROOT_PASSWORD={{ mysql_root_password }} \
          -e MYSQL_DATABASE={{ db_name }} \
          -p {{ mysql_port }}:3306 \
          -d mysql:8
      changed_when: false

    - name: Wait for MySQL to be healthy
      ansible.builtin.shell: |
        until docker exec a4-mysql mysqladmin ping -p{{ mysql_root_password }} --silent; do
          sleep 2
        done
      changed_when: false

    - name: Wait 10 seconds before creating DB user
      pause:
        seconds: 10

    - name: Create DB user with limited privileges
      shell: |
        docker exec a4-mysql bash -c "
          mysql -uroot -p{{ mysql_root_password }} -e \"
            CREATE USER IF NOT EXISTS '{{ db_user }}'@'%' IDENTIFIED BY '{{ db_pass }}';
            GRANT ALL PRIVILEGES ON {{ db_name }}.* TO '{{ db_user }}'@'%';
            FLUSH PRIVILEGES;
          \"
        "
      register: user_creation
      retries: 3
      delay: 5
      until: user_creation.rc == 0

    - name: Run initial Flyway migrations (Docker)
      ansible.builtin.shell: |
        docker run --rm \
          -v {{ playbook_dir }}/../flyway:/flyway \
          flyway/flyway:10 \
          -url=jdbc:mysql://{{ mysql_host }}:{{ mysql_port }}/{{ db_name }} \
          -user={{ db_user }} -password={{ db_pass }} \
          -mysql.allowPublicKeyRetrieval=true \
          -connectRetries=10 \
          -locations=filesystem:/flyway/migrations_initial migrate
      args:
        chdir: "{{ playbook_dir }}/.."



