name: CI Pipeline - Flyway + Pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: subscriptions
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -prootpass"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Wait for MySQL to start
        run: sleep 25

      - name: Verify MySQL connection
        run: |
          sudo apt-get install -y mysql-client
          mysql -h 127.0.0.1 -P 3306 -uroot -prootpass -e "SHOW DATABASES;"

      - name: Run Flyway migrations
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/flyway:/flyway \
            flyway/flyway:10 bash -c "\
              /flyway/flyway \
              -url=jdbc:mysql://127.0.0.1:3306/subscriptions \
              -user=root -password=rootpass \
              -mysql.allowPublicKeyRetrieval=true \
              -connectRetries=10 \
              -locations=filesystem:/flyway/migrations_initial \
              migrate"





      - name: Run Python Tests
        run: |
          pip install mysql-connector-python pytest
          pytest -v tests/
